apiVersion: v1
kind: ConfigMap
metadata:
  name: blog-config
data:
  DATABASE_HOST: "postgres-service"
  DATABASE_PORT: "5432"
  DATABASE_NAME: "blogdb"
  DJANGO_ALLOWED_HOSTS: "*" 
---
apiVersion: v1
kind: Secret
metadata:
  name: blog-secrets
type: Opaque
stringData:
  DATABASE_USER: "bloguser"
  DATABASE_PASSWORD: "supersecret"
  SECRET_KEY: "k8s-super-secret-key"